name: Hola mundo

on: [push]

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello word
        run: echo "Hello word"

  others:
    runs-on: ubuntu-latest

    steps:
    - name: LS
      run: ls -al